= Guided Solution
:experimental:

== Objectives

* Investigate why the RHEL 8 server upgrade to RHEL 9 via Leapp is failing in Red Hat Satellite 6.
* Solve the upgrade issue in the hands-on lab environment.

== Instructions

Run following instructions on `rhel81` system with `root` as user.

.Sample output:
----
[ec2-user@rhel81 ~]$ sudo su -
[root@rhel81 ~]#
----

. Try to list the available repos on the client and it fails with:
+
[source,bash,role=execute]
----
subscription-manager repos
----
+
.Sample output:
----
Repositories disabled by configuration.
----

. Change the value of `manage_repos` in `/etc/rhsm/rhsm.conf` to `1` instead of `0`.
+
[source,bash,role=execute]
----
subscription-manager refresh
----
+
.Sample output:
----
All local data refreshed
----

. Install the leapp utility via `dnf install leapp-upgrade` and then run `leapp preupgrade`.
+
[source,bash,role=execute]
----
dnf install leapp-upgrade -y
----
+
[source,bash,role=execute]
----
leapp preupgrade
----
+
.Sample output:
----
...
...
2025-02-10 10:57:15.999198 [ERROR] Actor: target_userspace_creator
Message: Unable to install RHEL 9 userspace packages.
...
...
...
----

. Sync and add the `9.x` minor `appstream` and `baseos` repos to the content view:
.. Get the satellite console details and credentials from `Lab Access Details` under `Info` tab from the demo platform.
.. Login to satellite web console.
.. Navigate to `Content` select menu:Content[Red Hat Repositories].
.. Search with `rhel-9-for-x86_64-baseos-rpms` and click btn:[rhel-9-for-x86_64-baseos-rpms] to view drop down options.
.. Click on the btn:[+] beside `x86_64 9.4` to enable `baseos` for `9.4` minor version or the supported minor version as per this https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/upgrading_from_rhel_8_to_rhel_9/index#con_supported-upgrade-paths_upgrading-from-rhel-8-to-rhel-9[doc,window=_blank]
.. Navigate to `Content` select menu:Content[Sync Status] and click btn:[Expand all].
.. Click on the checkbox for `baseos` for `9.4` and click btn:[Synchronize Now] at the bottom.

#Add screenshots wherever possible.

. Perform the previous steps for `appstream` as well:
.. Login to satellite web console.
.. Navigate to `Content` select menu:Content[Red Hat Repositories].
.. Search with `rhel-9-for-x86_64-appstream-rpms` and click btn:[rhel-9-for-x86_64-appstream-rpms] to view drop down options.
.. Click on the btn:[+] beside `x86_64 9.4` to enable `appstream` for `9.4` minor version or the supported minor version as per this https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/upgrading_from_rhel_8_to_rhel_9/index#con_supported-upgrade-paths_upgrading-from-rhel-8-to-rhel-9[doc,window=_blank]
.. Navigate to `Content` select menu:Content[Sync Status] and click btn:[Expand all].
.. Click on the checkbox for `appstream` for `9.4` and click btn:[Synchronize Now] at the bottom.

#Add screenshots wherever possible.

. Now add `baseos` and `appstream` for `9.4` repos to the content view:
.. menu:Content[LifeCycle > Content Views]
.. Click on btn:[leapp_8to9] content view and then navigate to `Repositories` tab.
.. Select the `Status` filter as `Not added`.
.. Select the `Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9.4` and `Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9.4` repos and then click btn:[Add repositories]
.. Click btn:[Publish new version] a new version of this content view.

#Add screenshots wherever possible.

. Run `leapp preupgrade` now.
+
[source,bash,role=execute]
----
leapp preupgrade
----
+
.Sample output:
----
...
...
OSError: [Errno 24] Too many open files
...
...
sqlite3.OperationalError: unable to open database file
...
...
----

. Run the below command to set the ulimit.
+
[source,bash,role=execute]
----
ulimit -n 16384
----

. Run `leapp preupgrade` again.
+
[source,bash,role=execute]
----
leapp preupgrade
----
+
.Sample output:
----
...
...
Complete!
...
Reports summary:
    Errors:              0
    Inhibitors:          0
...
...
----

. Once the `leapp preupgrade` completes with `0` errors and `0` inhibitors , run the `leapp upgrade`
+
[source,bash,role=execute]
----
leapp upgrade
----
+
.Sample output:
----
...
...
file /usr/lib64/engines-3/afalg.so from install of openssl-libs-1:3.0.7-28.el9_4.x86_64 conflicts with file from package openssl3-libs-3.2.2-2.1.el8.x86_64
...
...
----

. The `openssl3-libs-3.2.2-2.1.el8.x86_64` rpm is installed from EPEL repo and hence needs to be removed to fix this error.
+
[source,bash,role=execute]
----
yum remove openssl3-libs-3.2.2-2.1.el8.x86_64 -y
----

. Run the `leapp upgrade` again.
+
[source,bash,role=execute]
----
leapp upgrade
----
+
.Sample output:
----
...
...

Complete!
====> * add_upgrade_boot_entry
        Add new boot entry for Leapp provided initramfs.
A reboot is required to continue. Please reboot your system.
...
...
----

. Once `leapp upgrade` is successful and it prompts for reboot; reboot the system and confirm that the server is now booted with RHEL 9 kernel.
+
[NOTE]
This will take FIXME time to reflect the changes.
