= What’s in this break-fix?

== In this break-fix:

**Type of issue:**

A RHEL 8 server `rhel81` is registered to the satellite server and needs to be upgraded to RHEL 9 via Leapp.
But errors in `leapp preupgrade` and `leapp upgrade` need to be resolved before a successful upgrade to RHEL 9.

**What you should already know:**

- A Red Hat Certified System Administrator (RHCSA) or have equivalent experience administrating Red Hat Enterprise Linux 8 or 9.
- Administration of Red Hat Satellite 6.

**How break-fix training works:**

. Challenge yourself in the break-fix activity. It describes a problem scenario that's simulated in the lab environment where you can investigate and solve the problem.
. Follow up with the guided solution:
.. If you weren't able to solve the problem on your own, read and follow the instructions in the Guided Solution to complete this training.
.. If you were successful in solving the problem, read the solution for useful tips you can apply when solving similar problems.