= Break-fix Scenario

A RHEL 8 server `rhel81` is registered to the satellite server and needs to be upgraded to RHEL 9 via Leapp.
But errors in `leapp preupgrade` and `leapp upgrade` need to be resolved before a successful upgrade to RHEL 9.
Your job is to investigate the issue and ensure that RHEL 8 server is upgraded to RHEL 9.

Here is error the message:

.Sample output
----
[root@rhel81 ~]# leapp preupgrade
...
...
2025-02-10 10:57:15.999198 [ERROR] Actor: target_userspace_creator
Message: Unable to install RHEL 9 userspace packages.
...
...
...
----

== Objectives

* Investigate why the RHEL 8 server upgrade to RHEL 9 via Leapp is failing in Red Hat Satellite 6.
* Solve the upgrade issue in the hands-on lab environment.

== Recreate Scenario

To recreate this scenario, run the `lab` script on the `bastion` server.

[source,bash,role=execute]
----
lab break breakfix0
----

.Sample output
----
[lab-user@bastion ~]$ lab break breakfix0
Initiating /usr/local/bin/lab with option(s) break breakfix0
Completed /usr/local/bin/lab with option(s) break breakfix0 successfully
----

[NOTE]
It may take 2-3 minutes to complete.

== Success Criteria

Ensure the `leapp upgrade` command results in success and the `rhel81` server is upgraded to RHEL 9.

[source,bash,role=execute]
----
leapp upgrade
----

.Sample output:
----
...
...

Complete!
====> * add_upgrade_boot_entry
        Add new boot entry for Leapp provided initramfs.
A reboot is required to continue. Please reboot your system.
...
...
----